=== Tito5e/SkyblockDatabase/schemas/item.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://raw.githubusercontent.com/Tito5e/SkyblockDatabase/main/schemas/item.json",
    "type": "object",
    "required": [
        "id",
        "type",
        "name",
        "lore",
        "rarity",
        "sellable",
        "tradable",
        "auctionable",
        "reforgeable",
        "enchantable",
        "museum"
    ],
    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string"
        },
        "type": {
            "type": "string",
            "enum": [
                "ACCESSORY",

                "BELT",
                "BRACELET",
                "CLOAK",
                "GLOVES",
                "NECKLACE",

                "HELMET",
                "CHESTPLATE",
                "LEGGINGS",
                "BOOTS",

                "SWORD",
                "LONGSWORD",

                "BOW",
                "SHORTBOW",

                "WAND",

                "PICKAXE",
                "DRILL",
                "GAUNTLET",

                "AXE",

                "HOE",

                "SHOVEL",

                "FISHING_ROD",
                "FISHING_WEAPON",

                "SHEARS",

                "ARROW_POISON",
                "BAIT",
                "POWER_STONE",
                "REFORGE_STONE",

                "RIFT_TIMECHARM",
                "COSMETIC",
                "MOMENTO",
                "ITEM",
                "NO_TYPE"
            ]
        },
        "name": {
            "type": "string"
        },
        "lore": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "rarity": {
            "type": "string",
            "enum": [
                "COMMON",
                "UNCOMMON",
                "RARE",
                "EPIC",
                "LEGENDARY",
                "MYTHIC",
                "DIVINE",
                "ULTIMATE",
                "SPECIAL",
                "VERY_SPECIAL",
                "ADMIN"
            ]
        },

        "sellable": {
            "type": "boolean"
        },

        "tradable": {
            "type": "boolean"
        },

        "auctionable": {
            "type": "boolean"
        },

        "reforgeable": {
            "type": "boolean"
        },

        "enchantable": {
            "type": "boolean"
        },

        "museum": {
            "type": "boolean"
        },

        "status": {
            "$ref": "https://raw.githubusercontent.com/Tito5e/SkyblockDatabase/main/schemas/status.json"
        },

        "$schema": {
            "type": "string"
        }
    }
}

=== Tito5e/SkyblockDatabase/items/accessory/ABICASE_BLUE_BLUE.json
{
    "$schema": "https://raw.githubusercontent.com/Tito5e/SkyblockDatabase/main/schemas/item.json",
    "id": "ABICASE_BLUE_BLUE",
    "type": "ACCESSORY",
    "name": "Actually Blueâ„¢ Abicase",
    "lore": [
        "<gray>Grants <gold>+1 Magical Power",
        "<gray>per <green>2 <gray>contacts in your",
        "<gray>Abiphone.",
        "",
        "<dark_gray>Only ONE case will have an",
        "<dark_gray>effect while in accessory bag."
    ],
    "rarity": "RARE",

    "sellable": false,
    "tradable": true,
    "auctionable": true,
    "reforgeable": false,
    "enchantable": false,
    "museum": false,

    "status": {
        "mining_wisdom": 1.5
    }
}

=== Tito5e/SkyblockDatabase/items/accessory/AGARIMOO_ARTIFACT.json
{
    "$schema": "https://raw.githubusercontent.com/Tito5e/SkyblockDatabase/main/schemas/item.json",
    "id": "AGARIMOO_ARTIFACT",
    "type": "ACCESSORY",
    "name": "Agarimoo Artifact",
    "lore": [],
    "rarity": "RARE",

    "sellable": false,
    "tradable": true,
    "auctionable": true,
    "reforgeable": false,
    "enchantable": false,
    "museum": false,

    "status": {
        "fishing_wisdom": 1,
        "farming_wisdom": 1,
        "fishing_speed": 3
    }
}
